### ISSUE TITLE
Bug: Book cannot be marked as read nor reviewed

### ISSUE THREAD

**Issue by DenowRammy** [nperez0111/bookhive#6]
## Steps to reproduce
Log in
Go to affected book's page ( https://bookhive.buzz/books/bk_pVwue1z3fZxLTV48qfWY )
Click "Add to Shelf" and select "Have Read"

## Errors produced
The image on the page itself appears as a blank white image, displaying the alt text (also in white) "Cover of Ascendance of a Bookworm (Light Novel), Part 1 Volume 3"

Upon following reproduction steps, I receive the following error:
> 500
> Failed to record book
> 
> Error: Input buffer contains unsupported image format

**Comment by nperez0111** [comment]
I fixed this, in another change 👍
